<?php

namespace ApplicationMigrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140405211140 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->addSql("
            create or replace view vw_pipeline as
            select a.*, p.name as project_name, c.contact as client_name
            from articles a
            inner join projects p on (a.project_id = p.id)
            inner join clients c on (c.id = p.clients_id)
            inner join user_clients uc on (uc.client_id = c.id)
            inner join users u on (u.id = uc.user_id)
            order by due_date asc
        ");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->addSql("drop view vw_pipeline");
    }
}
