<?php

namespace ApplicationMigrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140405190023 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql("
            alter table clients add column contact varchar(100) not null
        ");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
